name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
  workflow_call:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          install-mode: "binary"
          skip-pkg-cache: true
